### PR TITLE
Captions on credential attributes

### PR DESCRIPTION
**Pull request by guilherme-funchal**
I rewrote the template profilecredentials.html to display captions on credential attributes.

### CODE REVIEW

**Review by ianco — COMMENTED** [review]
The changes look good, but for some reason your first commit updated every file in the repository.

**Review by ianco — CHANGES_REQUESTED** [review]
Can you see if you can get a clean pull request including only the files you changed?

**Comment by guilherme-funchal** [comment]
> The changes look good, but for some reason your first commit updated every file in the repository.

Hello, In fact, I did three separate commits and github joined, I don't know why. Sorry if I did something wrong, I'm not used to it "pull request", 
I will try to be more careful next time. I'll check why he changed 90 files.

**Comment by guilherme-funchal** [comment]
Apparently for something I should have done he changed the file permissions : 

https://github.com/guilherme-funchal/django-aries-community/commit/38939133480b16805f048c271c2f84dad7b92ad7#diff-41dafe794caa112ae5c8f67b1f54f0df

I will try to modify the property "git config core.filemode false" And I will check in the next commit.

If you want to give me a step by step of how you work I will follow to not create problems for you.

**Comment by ianco** [comment]
I think this is related to how I setup docker, to run mounting the local folders.

I think I should change this, so the files are instead copied into the docker container, so we don't need to change file permissions.

I can fix this today.

**Comment by ianco** [comment]
Hi Guilherme

I've updated the docker files so the code is loaded into the docker container, rather than running from a mounted folder.  You should be able to check out and run the dockers without having to change any file permissions.

Can you please:
- check out a fresh copy of the repository
- copy over the files you have changed
- check in and open up a new pull request?

Sorry for the inconvenience :-(  I just want to avoid unnecessary changes in the commit history.

Also, when you check in your code, can you please use the following flags on your git command:

git commit --signoff -S ...

The "--signoff" is required for some open source projects (e.g. all of Hyperledger projects) so it's a good practice.  The "-S" digitally signs your commit (you need to setup a signing key, you can read about it here:  https://help.github.com/en/github/authenticating-to-github/signing-commits) which is also a good practice to get into.

Thanks for getting involved!

**Comment by guilherme-funchal** [comment]
> Hi Guilherme
> 
> I've updated the docker files so the code is loaded into the docker container, rather than running from a mounted folder. You should be able to check out and run the dockers without having to change any file permissions.
> 
> Can you please:
> 
> * check out a fresh copy of the repository
> * copy over the files you have changed
> * check in and open up a new pull request?
> 
> Sorry for the inconvenience :-( I just want to avoid unnecessary changes in the commit history.
> 
> Also, when you check in your code, can you please use the following flags on your git command:
> 
> git commit --signoff -S ...
> 
> The "--signoff" is required for some open source projects (e.g. all of Hyperledger projects) so it's a good practice. The "-S" digitally signs your commit (you need to setup a signing key, you can read about it here: https://help.github.com/en/github/authenticating-to-github/signing-commits) which is also a good practice to get into.
> 
> Thanks for getting involved!

Hello Ian, How do you set up the development environment? Now that the folder is no longer mounted in place, how do you test code changes at runtime?

**Comment by ianco** [comment]
There are two ways to do this:  easiest is to setup the docker script so we can pass in an environment variable to specify "dev mode" or not.  The docker-compose.yml file would contain two definitions - django-aries and django-aries-dev - and then the manage script could start one or the other.  This still doesn't address the issue of git picking up changes to file permissions ...

The other way is to install everything locally and run local.  This is a bit more challenging.  There were instructions in the old django-indy-community project for this, I'll update them into django-aries-community.  Basically you need to clone and build a bunch of projects locally.  It's a bit more straightforward with Aries because it encapsulates all the Indy dependencies in the aca-py docker image.

I'll try to get these instructions updated over the weekend.

**Comment by guilherme-funchal** [comment]
I will then wait for you to update the document to set up my environment. In the meantime, review what I've already done and then start working on translations.

**Pull request closed without merging**
